### ISSUE TITLE
Stdin is blocked on Windows

### ISSUE THREAD

**Issue by Etto48** [dalance/termbg#25]
When using the library on Windows (both WindowsTerminal and VSCode integrated terminal) the program fails to detect the color and also blocks the Stdin until the next character is received. This is a significant problem when included in a TUI program because this behavior disables a lot of crossterm events. A possible workaround would be to identify the terminal as Windows instead of XtermCompatible when VSCode or WT are detected on Windows even if this could provide some wrong results. Another solution could be to mark the terminal as Unsupported and return an error. I can create a PR with one of these solutions if it's needed.

**Comment by dalance** [comment]
I had recognized unexpected char consuming of stdin, but I couldn't fix it.
Now I found the way to use non-blocking stdin, and implemented it.
Could you try `non_blocking_stdin` branch?

**Comment by dalance** [comment]
OK. I'll investigate about Windows API for non-blocking stdin.

**Comment by durbanlegend** [comment]
For some reason I only found this issue after going down the Windows rabbit hole myself.
I have been preparing a PR for this issue, with a non-blocking solution based on crossterm's event::read.
I'm still trying to figure out an automated test for it, otherwise I'm ready to go. The PR is based on a customisation I did for my own project, so it contains a few other changes, including a scopeguard to ensure state is restored and additional comments further explaining the issues with Windows. It also replaces the use of async_std with a simple synchronous loop, as I didn't want to incorporate the 216kB async_std as a dependency and don't consider it necessary. You may or may not choose to accept all these changes, but crucially it does contain a version of fn from_xterm that fixes the problem in all the testing I've done.
A piece of good news is that xterm is part of MS's strategic roadmap for Windows Terminal, and as of the currently available Windows Terminal (WT) 1.22 Preview, WT finally supports OSC10 and 11 colour queries, which up to now have *not* been part of its xterm compatibility. I've tested this too, and it works.
Regards, Don
